// Complete list of all 114 Surahs with metadata
export const SURAHS_METADATA = [
    { number: 1, name: "الفاتحة", englishName: "Al-Fatiha", banglaName: "আল-ফাতিহা", englishTranslation: "The Opening", banglaTranslation: "সূচনা", verses: 7, revelationType: "Meccan" as const },
    { number: 2, name: "البقرة", englishName: "Al-Baqarah", banglaName: "আল-বাকারা", englishTranslation: "The Cow", banglaTranslation: "গাভী", verses: 286, revelationType: "Medinan" as const },
    { number: 3, name: "آل عمران", englishName: "Ali 'Imran", banglaName: "আলে-ইমরান", englishTranslation: "Family of Imran", banglaTranslation: "ইমরানের পরিবার", verses: 200, revelationType: "Medinan" as const },
    { number: 4, name: "النساء", englishName: "An-Nisa", banglaName: "আন-নিসা", englishTranslation: "The Women", banglaTranslation: "নারী", verses: 176, revelationType: "Medinan" as const },
    { number: 5, name: "المائدة", englishName: "Al-Ma'idah", banglaName: "আল-মায়িদা", englishTranslation: "The Table", banglaTranslation: "খাবার টেবিল", verses: 120, revelationType: "Medinan" as const },
    { number: 6, name: "الأنعام", englishName: "Al-An'am", banglaName: "আল-আনআম", englishTranslation: "The Cattle", banglaTranslation: "গবাদি পশু", verses: 165, revelationType: "Meccan" as const },
    { number: 7, name: "الأعراف", englishName: "Al-A'raf", banglaName: "আল-আ'রাফ", englishTranslation: "The Heights", banglaTranslation: "উচ্চভূমি", verses: 206, revelationType: "Meccan" as const },
    { number: 8, name: "الأنفال", englishName: "Al-Anfal", banglaName: "আল-আনফাল", englishTranslation: "The Spoils of War", banglaTranslation: "যুদ্ধলব্ধ সম্পদ", verses: 75, revelationType: "Medinan" as const },
    { number: 9, name: "التوبة", englishName: "At-Tawbah", banglaName: "আত-তাওবা", englishTranslation: "The Repentance", banglaTranslation: "তওবা", verses: 129, revelationType: "Medinan" as const },
    { number: 10, name: "يونس", englishName: "Yunus", banglaName: "ইউনুস", englishTranslation: "Jonah", banglaTranslation: "ইউনুস", verses: 109, revelationType: "Meccan" as const },
    { number: 11, name: "هود", englishName: "Hud", banglaName: "হুদ", englishTranslation: "Hud", banglaTranslation: "হুদ", verses: 123, revelationType: "Meccan" as const },
    { number: 12, name: "يوسف", englishName: "Yusuf", banglaName: "ইউসুফ", englishTranslation: "Joseph", banglaTranslation: "ইউসুফ", verses: 111, revelationType: "Meccan" as const },
    { number: 13, name: "الرعد", englishName: "Ar-Ra'd", banglaName: "আর-রা'দ", englishTranslation: "The Thunder", banglaTranslation: "বজ্রপাত", verses: 43, revelationType: "Medinan" as const },
    { number: 14, name: "ابراهيم", englishName: "Ibrahim", banglaName: "ইবরাহীম", englishTranslation: "Abraham", banglaTranslation: "ইবরাহীম", verses: 52, revelationType: "Meccan" as const },
    { number: 15, name: "الحجر", englishName: "Al-Hijr", banglaName: "আল-হিজর", englishTranslation: "The Rocky Tract", banglaTranslation: "প্রস্তরময় ভূমি", verses: 99, revelationType: "Meccan" as const },
    { number: 16, name: "النحل", englishName: "An-Nahl", banglaName: "আন-নাহল", englishTranslation: "The Bee", banglaTranslation: "মৌমাছি", verses: 128, revelationType: "Meccan" as const },
    { number: 17, name: "الإسراء", englishName: "Al-Isra", banglaName: "আল-ইসরা", englishTranslation: "The Night Journey", banglaTranslation: "রাত্রি ভ্রমণ", verses: 111, revelationType: "Meccan" as const },
    { number: 18, name: "الكهف", englishName: "Al-Kahf", banglaName: "আল-কাহফ", englishTranslation: "The Cave", banglaTranslation: "গুহা", verses: 110, revelationType: "Meccan" as const },
    { number: 19, name: "مريم", englishName: "Maryam", banglaName: "মারইয়াম", englishTranslation: "Mary", banglaTranslation: "মারইয়াম", verses: 98, revelationType: "Meccan" as const },
    { number: 20, name: "طه", englishName: "Taha", banglaName: "ত্বা-হা", englishTranslation: "Ta-Ha", banglaTranslation: "ত্বা-হা", verses: 135, revelationType: "Meccan" as const },
    { number: 21, name: "الأنبياء", englishName: "Al-Anbya", banglaName: "আল-আম্বিয়া", englishTranslation: "The Prophets", banglaTranslation: "নবীগণ", verses: 112, revelationType: "Meccan" as const },
    { number: 22, name: "الحج", englishName: "Al-Hajj", banglaName: "আল-হজ্জ", englishTranslation: "The Pilgrimage", banglaTranslation: "হজ্জ", verses: 78, revelationType: "Medinan" as const },
    { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", banglaName: "আল-মুমিনূন", englishTranslation: "The Believers", banglaTranslation: "মুমিনগণ", verses: 118, revelationType: "Meccan" as const },
    { number: 24, name: "النور", englishName: "An-Nur", banglaName: "আন-নূর", englishTranslation: "The Light", banglaTranslation: "আলো", verses: 64, revelationType: "Medinan" as const },
    { number: 25, name: "الفرقان", englishName: "Al-Furqan", banglaName: "আল-ফুরকান", englishTranslation: "The Criterion", banglaTranslation: "সত্য-মিথ্যার পার্থক্যকারী", verses: 77, revelationType: "Meccan" as const },
    { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", banglaName: "আশ-শুআরা", englishTranslation: "The Poets", banglaTranslation: "কবিগণ", verses: 227, revelationType: "Meccan" as const },
    { number: 27, name: "النمل", englishName: "An-Naml", banglaName: "আন-নামল", englishTranslation: "The Ant", banglaTranslation: "পিপীলিকা", verses: 93, revelationType: "Meccan" as const },
    { number: 28, name: "القصص", englishName: "Al-Qasas", banglaName: "আল-কাসাস", englishTranslation: "The Stories", banglaTranslation: "কাহিনী", verses: 88, revelationType: "Meccan" as const },
    { number: 29, name: "العنكبوت", englishName: "Al-'Ankabut", banglaName: "আল-আনকাবুত", englishTranslation: "The Spider", banglaTranslation: "মাকড়সা", verses: 69, revelationType: "Meccan" as const },
    { number: 30, name: "الروم", englishName: "Ar-Rum", banglaName: "আর-রূম", englishTranslation: "The Romans", banglaTranslation: "রোমানরা", verses: 60, revelationType: "Meccan" as const },
    { number: 31, name: "لقمان", englishName: "Luqman", banglaName: "লুকমান", englishTranslation: "Luqman", banglaTranslation: "লুকমান", verses: 34, revelationType: "Meccan" as const },
    { number: 32, name: "السجدة", englishName: "As-Sajdah", banglaName: "আস-সাজদাহ", englishTranslation: "The Prostration", banglaTranslation: "সিজদা", verses: 30, revelationType: "Meccan" as const },
    { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", banglaName: "আল-আহযাব", englishTranslation: "The Combined Forces", banglaTranslation: "সম্মিলিত বাহিনী", verses: 73, revelationType: "Medinan" as const },
    { number: 34, name: "سبإ", englishName: "Saba", banglaName: "সাবা", englishTranslation: "Sheba", banglaTranslation: "সাবা", verses: 54, revelationType: "Meccan" as const },
    { number: 35, name: "فاطر", englishName: "Fatir", banglaName: "ফাতির", englishTranslation: "Originator", banglaTranslation: "সৃষ্টিকর্তা", verses: 45, revelationType: "Meccan" as const },
    { number: 36, name: "يس", englishName: "Ya-Sin", banglaName: "ইয়া-সীন", englishTranslation: "Ya Sin", banglaTranslation: "ইয়া-সীন", verses: 83, revelationType: "Meccan" as const },
    { number: 37, name: "الصافات", englishName: "As-Saffat", banglaName: "আস-সাফফাত", englishTranslation: "Those Ranges in Ranks", banglaTranslation: "সারিবদ্ধ", verses: 182, revelationType: "Meccan" as const },
    { number: 38, name: "ص", englishName: "Sad", banglaName: "সোয়াদ", englishTranslation: "The Letter Sad", banglaTranslation: "সোয়াদ", verses: 88, revelationType: "Meccan" as const },
    { number: 39, name: "الزمر", englishName: "Az-Zumar", banglaName: "আয-যুমার", englishTranslation: "The Troops", banglaTranslation: "দলসমূহ", verses: 75, revelationType: "Meccan" as const },
    { number: 40, name: "غافر", englishName: "Ghafir", banglaName: "গাফির", englishTranslation: "The Forgiver", banglaTranslation: "ক্ষমাশীল", verses: 85, revelationType: "Meccan" as const },
    { number: 41, name: "فصلت", englishName: "Fussilat", banglaName: "ফুসসিলাত", englishTranslation: "Explained in Detail", banglaTranslation: "সুস্পষ্ট বিবরণ", verses: 54, revelationType: "Meccan" as const },
    { number: 42, name: "الشورى", englishName: "Ash-Shuraa", banglaName: "আশ-শূরা", englishTranslation: "The Consultation", banglaTranslation: "পরামর্শ", verses: 53, revelationType: "Meccan" as const },
    { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", banglaName: "আয-যুখরুফ", englishTranslation: "The Ornaments of Gold", banglaTranslation: "স্বর্ণালংকার", verses: 89, revelationType: "Meccan" as const },
    { number: 44, name: "الدخان", englishName: "Ad-Dukhan", banglaName: "আদ-দুখান", englishTranslation: "The Smoke", banglaTranslation: "ধোঁয়া", verses: 59, revelationType: "Meccan" as const },
    { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", banglaName: "আল-জাসিয়া", englishTranslation: "The Crouching", banglaTranslation: "নতজানু", verses: 37, revelationType: "Meccan" as const },
    { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", banglaName: "আল-আহকাফ", englishTranslation: "The Wind-Curved Sandhills", banglaTranslation: "বালুর টিলা", verses: 35, revelationType: "Meccan" as const },
    { number: 47, name: "محمد", englishName: "Muhammad", banglaName: "মুহাম্মাদ", englishTranslation: "Muhammad", banglaTranslation: "মুহাম্মাদ", verses: 38, revelationType: "Medinan" as const },
    { number: 48, name: "الفتح", englishName: "Al-Fath", banglaName: "আল-ফাতহ", englishTranslation: "The Victory", banglaTranslation: "বিজয়", verses: 29, revelationType: "Medinan" as const },
    { number: 49, name: "الحجرات", englishName: "Al-Hujurat", banglaName: "আল-হুজুরাত", englishTranslation: "The Rooms", banglaTranslation: "কক্ষসমূহ", verses: 18, revelationType: "Medinan" as const },
    { number: 50, name: "ق", englishName: "Qaf", banglaName: "কাফ", englishTranslation: "The Letter Qaf", banglaTranslation: "কাফ", verses: 45, revelationType: "Meccan" as const },
    { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", banglaName: "আয-যারিয়াত", englishTranslation: "The Winnowing Winds", banglaTranslation: "বায়ু", verses: 60, revelationType: "Meccan" as const },
    { number: 52, name: "الطور", englishName: "At-Tur", banglaName: "আত-তূর", englishTranslation: "The Mount", banglaTranslation: "পর্বত", verses: 49, revelationType: "Meccan" as const },
    { number: 53, name: "النجم", englishName: "An-Najm", banglaName: "আন-নাজম", englishTranslation: "The Star", banglaTranslation: "নক্ষত্র", verses: 62, revelationType: "Meccan" as const },
    { number: 54, name: "القمر", englishName: "Al-Qamar", banglaName: "আল-কামার", englishTranslation: "The Moon", banglaTranslation: "চন্দ্র", verses: 55, revelationType: "Meccan" as const },
    { number: 55, name: "الرحمن", englishName: "Ar-Rahman", banglaName: "আর-রহমান", englishTranslation: "The Beneficent", banglaTranslation: "পরম করুণাময়", verses: 78, revelationType: "Medinan" as const },
    { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", banglaName: "আল-ওয়াকিয়া", englishTranslation: "The Inevitable", banglaTranslation: "অনিবার্য ঘটনা", verses: 96, revelationType: "Meccan" as const },
    { number: 57, name: "الحديد", englishName: "Al-Hadid", banglaName: "আল-হাদীদ", englishTranslation: "The Iron", banglaTranslation: "লোহা", verses: 29, revelationType: "Medinan" as const },
    { number: 58, name: "المجادلة", englishName: "Al-Mujadila", banglaName: "আল-মুজাদালা", englishTranslation: "The Pleading Woman", banglaTranslation: "বিতর্ককারিণী", verses: 22, revelationType: "Medinan" as const },
    { number: 59, name: "الحشر", englishName: "Al-Hashr", banglaName: "আল-হাশর", englishTranslation: "The Exile", banglaTranslation: "সমাবেশ", verses: 24, revelationType: "Medinan" as const },
    { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", banglaName: "আল-মুমতাহিনা", englishTranslation: "She That is to be Examined", banglaTranslation: "পরীক্ষিতা", verses: 13, revelationType: "Medinan" as const },
    { number: 61, name: "الصف", englishName: "As-Saf", banglaName: "আস-সফ", englishTranslation: "The Ranks", banglaTranslation: "সারি", verses: 14, revelationType: "Medinan" as const },
    { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", banglaName: "আল-জুমুআহ", englishTranslation: "The Congregation", banglaTranslation: "জুমআহ", verses: 11, revelationType: "Medinan" as const },
    { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", banglaName: "আল-মুনাফিকূন", englishTranslation: "The Hypocrites", banglaTranslation: "মুনাফিকগণ", verses: 11, revelationType: "Medinan" as const },
    { number: 64, name: "التغابن", englishName: "At-Taghabun", banglaName: "আত-তাগাবুন", englishTranslation: "The Mutual Disillusion", banglaTranslation: "পরস্পর প্রতারণা", verses: 18, revelationType: "Medinan" as const },
    { number: 65, name: "الطلاق", englishName: "At-Talaq", banglaName: "আত-ত্বলাক", englishTranslation: "The Divorce", banglaTranslation: "তালাক", verses: 12, revelationType: "Medinan" as const },
    { number: 66, name: "التحريم", englishName: "At-Tahrim", banglaName: "আত-তাহরীম", englishTranslation: "The Prohibition", banglaTranslation: "নিষিদ্ধকরণ", verses: 12, revelationType: "Medinan" as const },
    { number: 67, name: "الملك", englishName: "Al-Mulk", banglaName: "আল-মুলক", englishTranslation: "The Sovereignty", banglaTranslation: "রাজত্ব", verses: 30, revelationType: "Meccan" as const },
    { number: 68, name: "القلم", englishName: "Al-Qalam", banglaName: "আল-কলম", englishTranslation: "The Pen", banglaTranslation: "কলম", verses: 52, revelationType: "Meccan" as const },
    { number: 69, name: "الحاقة", englishName: "Al-Haqqah", banglaName: "আল-হাক্কাহ", englishTranslation: "The Reality", banglaTranslation: "নিশ্চিত সত্য", verses: 52, revelationType: "Meccan" as const },
    { number: 70, name: "المعارج", englishName: "Al-Ma'arij", banglaName: "আল-মাআরিজ", englishTranslation: "The Ascending Stairways", banglaTranslation: "ঊর্ধ্বগামী সিঁড়ি", verses: 44, revelationType: "Meccan" as const },
    { number: 71, name: "نوح", englishName: "Nuh", banglaName: "নূহ", englishTranslation: "Noah", banglaTranslation: "নূহ", verses: 28, revelationType: "Meccan" as const },
    { number: 72, name: "الجن", englishName: "Al-Jinn", banglaName: "আল-জিন", englishTranslation: "The Jinn", banglaTranslation: "জিন", verses: 28, revelationType: "Meccan" as const },
    { number: 73, name: "المزمل", englishName: "Al-Muzzammil", banglaName: "আল-মুযযাম্মিল", englishTranslation: "The Enshrouded One", banglaTranslation: "আবৃতকারী", verses: 20, revelationType: "Meccan" as const },
    { number: 74, name: "المدثر", englishName: "Al-Muddaththir", banglaName: "আল-মুদ্দাসসির", englishTranslation: "The Cloaked One", banglaTranslation: "বস্ত্রাবৃত", verses: 56, revelationType: "Meccan" as const },
    { number: 75, name: "القيامة", englishName: "Al-Qiyamah", banglaName: "আল-কিয়ামাহ", englishTranslation: "The Resurrection", banglaTranslation: "পুনরুত্থান", verses: 40, revelationType: "Meccan" as const },
    { number: 76, name: "الانسان", englishName: "Al-Insan", banglaName: "আল-ইনসান", englishTranslation: "The Man", banglaTranslation: "মানুষ", verses: 31, revelationType: "Medinan" as const },
    { number: 77, name: "المرسلات", englishName: "Al-Mursalat", banglaName: "আল-মুরসালাত", englishTranslation: "The Emissaries", banglaTranslation: "প্রেরিতগণ", verses: 50, revelationType: "Meccan" as const },
    { number: 78, name: "النبإ", englishName: "An-Naba", banglaName: "আন-নাবা", englishTranslation: "The Tidings", banglaTranslation: "মহাসংবাদ", verses: 40, revelationType: "Meccan" as const },
    { number: 79, name: "النازعات", englishName: "An-Nazi'at", banglaName: "আন-নাযিআত", englishTranslation: "Those Who Drag Forth", banglaTranslation: "যারা টেনে নিয়ে যায়", verses: 46, revelationType: "Meccan" as const },
    { number: 80, name: "عبس", englishName: "Abasa", banglaName: "আবাসা", englishTranslation: "He Frowned", banglaTranslation: "তিনি ভ্রুকুটি করলেন", verses: 42, revelationType: "Meccan" as const },
    { number: 81, name: "التكوير", englishName: "At-Takwir", banglaName: "আত-তাকভীর", englishTranslation: "The Overthrowing", banglaTranslation: "অন্ধকারাচ্ছন্ন", verses: 29, revelationType: "Meccan" as const },
    { number: 82, name: "الإنفطار", englishName: "Al-Infitar", banglaName: "আল-ইনফিত্বার", englishTranslation: "The Cleaving", banglaTranslation: "বিদীর্ণ হওয়া", verses: 19, revelationType: "Meccan" as const },
    { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", banglaName: "আল-মুতাফফিফীন", englishTranslation: "The Defrauding", banglaTranslation: "প্রতারকগণ", verses: 36, revelationType: "Meccan" as const },
    { number: 84, name: "الإنشقاق", englishName: "Al-Inshiqaq", banglaName: "আল-ইনশিকাক", englishTranslation: "The Sundering", banglaTranslation: "বিদারিত হওয়া", verses: 25, revelationType: "Meccan" as const },
    { number: 85, name: "البروج", englishName: "Al-Buruj", banglaName: "আল-বুরূজ", englishTranslation: "The Mansions of the Stars", banglaTranslation: "নক্ষত্ররাজি", verses: 22, revelationType: "Meccan" as const },
    { number: 86, name: "الطارق", englishName: "At-Tariq", banglaName: "আত-ত্বারিক", englishTranslation: "The Morning Star", banglaTranslation: "রাত্রিকালীন আগন্তুক", verses: 17, revelationType: "Meccan" as const },
    { number: 87, name: "الأعلى", englishName: "Al-A'la", banglaName: "আল-আ'লা", englishTranslation: "The Most High", banglaTranslation: "সর্বোচ্চ", verses: 19, revelationType: "Meccan" as const },
    { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", banglaName: "আল-গাশিয়াহ", englishTranslation: "The Overwhelming", banglaTranslation: "বিস্তৃতকারিণী", verses: 26, revelationType: "Meccan" as const },
    { number: 89, name: "الفجر", englishName: "Al-Fajr", banglaName: "আল-ফাজর", englishTranslation: "The Dawn", banglaTranslation: "প্রভাত", verses: 30, revelationType: "Meccan" as const },
    { number: 90, name: "البلد", englishName: "Al-Balad", banglaName: "আল-বালাদ", englishTranslation: "The City", banglaTranslation: "নগর", verses: 20, revelationType: "Meccan" as const },
    { number: 91, name: "الشمس", englishName: "Ash-Shams", banglaName: "আশ-শামস", englishTranslation: "The Sun", banglaTranslation: "সূর্য", verses: 15, revelationType: "Meccan" as const },
    { number: 92, name: "الليل", englishName: "Al-Layl", banglaName: "আল-লাইল", englishTranslation: "The Night", banglaTranslation: "রাত্রি", verses: 21, revelationType: "Meccan" as const },
    { number: 93, name: "الضحى", englishName: "Ad-Duhaa", banglaName: "আদ-দুহা", englishTranslation: "The Morning Hours", banglaTranslation: "পূর্বাহ্ন", verses: 11, revelationType: "Meccan" as const },
    { number: 94, name: "الشرح", englishName: "Ash-Sharh", banglaName: "আশ-শারহ", englishTranslation: "The Relief", banglaTranslation: "প্রশস্ততা", verses: 8, revelationType: "Meccan" as const },
    { number: 95, name: "التين", englishName: "At-Tin", banglaName: "আত-তীন", englishTranslation: "The Fig", banglaTranslation: "ডুমুর", verses: 8, revelationType: "Meccan" as const },
    { number: 96, name: "العلق", englishName: "Al-Alaq", banglaName: "আল-আলাক", englishTranslation: "The Clot", banglaTranslation: "জমাট রক্ত", verses: 19, revelationType: "Meccan" as const },
    { number: 97, name: "القدر", englishName: "Al-Qadr", banglaName: "আল-কদর", englishTranslation: "The Power", banglaTranslation: "মহিমান্বিত", verses: 5, revelationType: "Meccan" as const },
    { number: 98, name: "البينة", englishName: "Al-Bayyinah", banglaName: "আল-বাইয়্যিনাহ", englishTranslation: "The Clear Proof", banglaTranslation: "সুস্পষ্ট প্রমাণ", verses: 8, revelationType: "Medinan" as const },
    { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", banglaName: "আয-যিলযাল", englishTranslation: "The Earthquake", banglaTranslation: "ভূমিকম্প", verses: 8, revelationType: "Medinan" as const },
    { number: 100, name: "العاديات", englishName: "Al-Adiyat", banglaName: "আল-আদিয়াত", englishTranslation: "The Courser", banglaTranslation: "দ্রুতগামী অশ্ব", verses: 11, revelationType: "Meccan" as const },
    { number: 101, name: "القارعة", englishName: "Al-Qari'ah", banglaName: "আল-কারিআহ", englishTranslation: "The Calamity", banglaTranslation: "মহাপ্রলয়", verses: 11, revelationType: "Meccan" as const },
    { number: 102, name: "التكاثر", englishName: "At-Takathur", banglaName: "আত-তাকাসুর", englishTranslation: "The Rivalry in World Increase", banglaTranslation: "প্রাচুর্যের প্রতিযোগিতা", verses: 8, revelationType: "Meccan" as const },
    { number: 103, name: "العصر", englishName: "Al-Asr", banglaName: "আল-আসর", englishTranslation: "The Declining Day", banglaTranslation: "সময়", verses: 3, revelationType: "Meccan" as const },
    { number: 104, name: "الهمزة", englishName: "Al-Humazah", banglaName: "আল-হুমাযাহ", englishTranslation: "The Traducer", banglaTranslation: "পরনিন্দাকারী", verses: 9, revelationType: "Meccan" as const },
    { number: 105, name: "الفيل", englishName: "Al-Fil", banglaName: "আল-ফীল", englishTranslation: "The Elephant", banglaTranslation: "হাতী", verses: 5, revelationType: "Meccan" as const },
    { number: 106, name: "قريش", englishName: "Quraysh", banglaName: "কুরাইশ", englishTranslation: "Quraysh", banglaTranslation: "কুরাইশ", verses: 4, revelationType: "Meccan" as const },
    { number: 107, name: "الماعون", englishName: "Al-Ma'un", banglaName: "আল-মাউন", englishTranslation: "The Small Kindnesses", banglaTranslation: "সাহায্য-সহযোগিতা", verses: 7, revelationType: "Meccan" as const },
    { number: 108, name: "الكوثر", englishName: "Al-Kawthar", banglaName: "আল-কাওসার", englishTranslation: "The Abundance", banglaTranslation: "প্রাচুর্য", verses: 3, revelationType: "Meccan" as const },
    { number: 109, name: "الكافرون", englishName: "Al-Kafirun", banglaName: "আল-কাফিরূন", englishTranslation: "The Disbelievers", banglaTranslation: "অবিশ্বাসীগণ", verses: 6, revelationType: "Meccan" as const },
    { number: 110, name: "النصر", englishName: "An-Nasr", banglaName: "আন-নাসর", englishTranslation: "The Divine Support", banglaTranslation: "সাহায্য", verses: 3, revelationType: "Medinan" as const },
    { number: 111, name: "المسد", englishName: "Al-Masad", banglaName: "আল-মাসাদ", englishTranslation: "The Palm Fiber", banglaTranslation: "পাম ফাইবার", verses: 5, revelationType: "Meccan" as const },
    { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", banglaName: "আল-ইখলাস", englishTranslation: "The Sincerity", banglaTranslation: "একনিষ্ঠতা", verses: 4, revelationType: "Meccan" as const },
    { number: 113, name: "الفلق", englishName: "Al-Falaq", banglaName: "আল-ফালাক", englishTranslation: "The Daybreak", banglaTranslation: "প্রভাত", verses: 5, revelationType: "Meccan" as const },
    { number: 114, name: "الناس", englishName: "An-Nas", banglaName: "আন-নাস", englishTranslation: "Mankind", banglaTranslation: "মানবজাতি", verses: 6, revelationType: "Meccan" as const },
];
